import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { ResolvedMcpServer } from "@/shared/contracts";

interface BridgeServer {
  name: string;
  timeoutMs: number;
  disabledTools?: string[];
  transport: ResolvedMcpServer["transport"];
}

/**
 * Pi's RPC mode has no native MCP support and the installed `pi` CLI does not
 * ship `@modelcontextprotocol/sdk`, so Poracode's resolved MCP servers are
 * bridged by generating a self-contained pi extension. The extension runs
 * inside the pi subprocess, speaks MCP directly (stdio via child_process,
 * HTTP/SSE via fetch — no external imports, so it also works once Poracode's
 * own node_modules is packed into an asar), and registers each server tool as
 * a Pi custom tool named `mcp__<server>__<tool>`.
 */
export async function writePiMcpExtension(servers: readonly ResolvedMcpServer[]): Promise<string> {
  const bridgeServers: BridgeServer[] = servers.map((server) => ({
    name: server.name,
    timeoutMs: server.timeoutMs,
    ...(server.disabledTools?.length ? { disabledTools: server.disabledTools } : {}),
    transport: server.transport,
  }));
  const dir = mkdtempSync(join(tmpdir(), "poracode-pi-mcp-"));
  const extensionPath = join(dir, "poracode-mcp-bridge.mjs");
  writeFileSync(extensionPath, buildExtensionSource(bridgeServers), "utf8");
  return extensionPath;
}

function buildExtensionSource(servers: BridgeServer[]): string {
  return `// Generated by Y Space — bridges Y Space MCP servers into Pi as custom tools.
import { spawn } from "node:child_process";

const SERVERS = ${JSON.stringify(servers)};

function sanitize(name) {
  return String(name).replace(/[^a-zA-Z0-9_-]/g, "_");
}

function withTimeout(promise, ms, label) {
  if (!ms) return promise;
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error(label + " timed out after " + ms + "ms")), ms);
    promise.then(
      (value) => { clearTimeout(timer); resolve(value); },
      (error) => { clearTimeout(timer); reject(error); },
    );
  });
}

class StdioClient {
  constructor(server) {
    const t = server.transport;
    this.child = spawn(t.command, t.args ?? [], {
      ...(t.cwd ? { cwd: t.cwd } : {}),
      env: { ...process.env, ...(t.env ?? {}) },
      stdio: ["pipe", "pipe", "pipe"],
    });
    this.child.on("error", () => undefined);
    this.child.stderr?.on("data", () => undefined);
    this.buffer = "";
    this.pending = new Map();
    this.seq = 0;
    this.child.stdout.on("data", (chunk) => this.onData(String(chunk)));
  }
  onData(chunk) {
    this.buffer += chunk;
    let index;
    while ((index = this.buffer.indexOf("\\n")) >= 0) {
      const line = this.buffer.slice(0, index).trim();
      this.buffer = this.buffer.slice(index + 1);
      if (!line) continue;
      let message;
      try { message = JSON.parse(line); } catch { continue; }
      if (message.id != null && this.pending.has(message.id)) {
        const pending = this.pending.get(message.id);
        this.pending.delete(message.id);
        if (message.error) pending.reject(new Error(message.error.message || "MCP error"));
        else pending.resolve(message.result);
      }
    }
  }
  write(message) {
    this.child.stdin.write(JSON.stringify(message) + "\\n");
  }
  request(method, params, timeoutMs) {
    const id = ++this.seq;
    const promise = new Promise((resolve, reject) => {
      this.pending.set(id, { resolve, reject });
      this.write({ jsonrpc: "2.0", id, method, ...(params !== undefined ? { params } : {}) });
    });
    return withTimeout(promise, timeoutMs, method);
  }
  notify(method, params) {
    this.write({ jsonrpc: "2.0", method, ...(params !== undefined ? { params } : {}) });
  }
  close() {
    try { this.child.kill(); } catch { /* already gone */ }
  }
}

class HttpClient {
  constructor(server) {
    const t = server.transport;
    this.url = t.url;
    this.headers = t.headers ?? {};
    this.sessionId = undefined;
    this.seq = 0;
  }
  async request(method, params, timeoutMs) {
    const id = ++this.seq;
    const response = await fetch(this.url, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        accept: "application/json, text/event-stream",
        ...this.headers,
        ...(this.sessionId ? { "mcp-session-id": this.sessionId } : {}),
      },
      body: JSON.stringify({ jsonrpc: "2.0", id, method, ...(params !== undefined ? { params } : {}) }),
      ...(timeoutMs ? { signal: AbortSignal.timeout(timeoutMs) } : {}),
    });
    const sessionId = response.headers.get("mcp-session-id");
    if (sessionId) this.sessionId = sessionId;
    const contentType = response.headers.get("content-type") || "";
    if (contentType.includes("text/event-stream")) {
      const text = await response.text();
      for (const line of text.split(/\\r?\\n/)) {
        if (!line.startsWith("data:")) continue;
        let message;
        try { message = JSON.parse(line.slice(5).trim()); } catch { continue; }
        if (message.id === id) {
          if (message.error) throw new Error(message.error.message || "MCP error");
          return message.result;
        }
      }
      throw new Error("MCP server returned no matching response for " + method);
    }
    const message = await response.json();
    if (message.error) throw new Error(message.error.message || "MCP error");
    return message.result;
  }
  notify() { /* stateless HTTP needs no notifications */ }
  close() {}
}

async function connect(server) {
  const client = server.transport.type === "stdio" ? new StdioClient(server) : new HttpClient(server);
  await client.request(
    "initialize",
    { protocolVersion: "2024-11-05", capabilities: {}, clientInfo: { name: "poracode-pi-mcp", version: "1.0.0" } },
    server.timeoutMs,
  );
  client.notify("notifications/initialized", {});
  return client;
}

async function listTools(client, timeoutMs) {
  const tools = [];
  let cursor;
  do {
    const result = await client.request("tools/list", cursor ? { cursor } : {}, timeoutMs);
    for (const tool of result?.tools ?? []) tools.push(tool);
    cursor = result?.nextCursor;
  } while (cursor);
  return tools;
}

function toPiResult(result) {
  const content = [];
  for (const entry of result?.content ?? []) {
    if (entry?.type === "text" && typeof entry.text === "string") {
      content.push({ type: "text", text: entry.text });
    } else if (entry?.type === "image" && typeof entry.data === "string" && typeof entry.mimeType === "string") {
      content.push({ type: "image", data: entry.data, mimeType: entry.mimeType });
    }
  }
  if (result?.isError === true) {
    const message = content.filter((entry) => entry.type === "text").map((entry) => entry.text).join("\\n");
    throw new Error(message || "MCP tool failed");
  }
  return {
    content: content.length > 0 ? content : [{ type: "text", text: JSON.stringify(result?.structuredContent ?? {}) }],
    details: result,
  };
}

export default async function poracodeMcpBridge(pi) {
  for (const server of SERVERS) {
    let client;
    try {
      client = await connect(server);
      const disabled = new Set(server.disabledTools ?? []);
      const tools = await listTools(client, server.timeoutMs);
      for (const tool of tools) {
        if (disabled.has(tool.name)) continue;
        const name = "mcp__" + sanitize(server.name) + "__" + sanitize(tool.name);
        pi.registerTool({
          name,
          label: server.name + ": " + (tool.title ?? tool.name),
          description: tool.description ?? ("Run " + tool.name + " on the " + server.name + " MCP server."),
          parameters: tool.inputSchema ?? { type: "object", properties: {} },
          execute: async (_toolCallId, params) => {
            const result = await client.request("tools/call", { name: tool.name, arguments: params ?? {} }, server.timeoutMs);
            return toPiResult(result);
          },
        });
      }
    } catch (error) {
      console.error("[poracode-mcp] unable to bridge MCP server " + server.name + ": " + (error?.message ?? error));
    }
  }
}
`;
}
